language: node_js
os: osx
node_js:
  - '10'
env:
  - TRAVIS_SECURE_ENV_VARS=true TIMEOUT=1000 CAMPFIRE_TOKEN=abc123
  matrix:
    - secure: "QRE3RGZDAHk5jwncMzl19B8yIryrHlvEgx5aZ4whDR35QyEpM7NmiErzEKw04wWn8HHHwo9+G8pyoizBtNPDueu521dZTR4UX206sUjXsGNB32cIWSudEy/Kl1gFh4uHEW84IVKl5uufLQVOwuBWdwGyNtJv2NAxu97G2/nWhgm/nyOXL5p28etXb2mvrWFNXsmWtGPPcr6ZRVLqAT+VYLOwOlHpF3YdvNnUEskdGamFrOHLfJBqVfknmEvenaQy+k51C4WOGCVztPbEr5S6uq9/h3UbN1FuRlGOX9OSCla89KGj4efGjhLbm9EnFtoZYF0ylGMQRz7IQasr1VKinyaP7e2voJZCIeRfyl9RhlU+KsAS7TXf70HSXZ5x29KcXW5jtVtVKyBPGTF2g0BEXG6xvSrALetbArE3f4Fo8NUCdy7+dHBtNFhqTBsoTfmkZHbplxMYFR6++ZhFafekq8XqZDXYBeTZLQWqkCIYoHRdql+9u7FehlGyQou139FheqWqMtQbXIDaMk6IBMxheSpYfq6z0cMIvbNhlnxpx528Zy+0TnMU+x24IsvbUENElgvHgkPCp4q8B2astMRHYbTHeTkv9B5GSprM/mBilwj20OiHnW28ORoOgAtV6XEG9NE76JmMAc4ThgkxWWKIzRnGlSn9xRnxZuVS21w+S5k="
matrix:
  fast_finish: true
cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"
script:
  - yarn dist
