language: node_js
os: osx
node_js:
- '10'
env:
  matrix:
  - secure: oxxvBsY0YT0h+4aHNQPbZ3ZgIQdsdowA282UEgQcs0QHwgCioQaiTTdSTzZ3vo+PkRXKUZ89MfiwGtBe38BKQBcjvqRvyKYIekmpXRNH4hh78MqEjXlnFlI9f68RO8pyDDWhD0y1r43ZCBxf6JCW10dJDWxWRUoD+yH3k+MaJC09cYYG4TYRQyvEbQHpxY8ilD2zTI6dqhK+3cNCGmS0R1jOOAL92Siw1wmIB8IOyAgw09istGRLZ4pVybUmrSXqrKQPftQZYvgQnHIyu7vk1Bqj1gKwibNAHuCKkXvAEDyZEqAkZKfhHO/VPAiRagA1WEAT9f35gDPfZi4c6fY1stFTAZVVqGgIEL4wAj0jHMsUZrEqjjGSxIddhlKg3FZ1p2ESspRS8FZh1qZxgHMG9qIuzXUdf5t/2+0XnPp1Enu2Oox1LPaKk9vea6XUohYynd7UNmMoKotnbCXNbxZgxTSekcBVaT0h4aDANpwJ/akWZ/iWD7kP25wH05NDT1IX4VNiSRYwxDUR+JvIL5sT9tEyYcCc/++1RVaob/sSfQ31O7QJlSlsi+bIGpAaCilfHr0VFTECkAlsX88dBz5VbeNVJ5/3wiyanUbeEuvm/aBWa0TC0WT/5EZVMA1B/0WvuWZPm150tp29d/wA7Rq/FlU9jCknP1+V8l7DV7xXKe8=
matrix:
  fast_finish: true
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script:
- yarn dist
