language: node_js
os: osx
node_js:
  - '10'
matrix:
  fast_finish: true
cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"
script:
  - yarn dist
