os: unstable	
cache:	  
  - node_modules
environment:
  matrix:
    - nodejs_version: 10
  GH_TOKEN:
    secure: NOoKKL7ILtkNaaJmZVEbbl9X4zND5YGw3s5h0V+qdvQGSJi1tZI5OvNYS9OzzBa9

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn --ignore-engines

matrix:
  fast_finish: true

build: off

shallow_clone: true

test_script:
  - node --version
  - yarn --version
  - yarn build