os: unstable	
cache:	  
  - node_modules
environment:
  matrix:
    - nodejs_version: 10

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn --ignore-engines

matrix:
  fast_finish: true

build: off

shallow_clone: true

test_script:
  - node --version
  - yarn --version
  - yarn build